/* AI Teams - peer-to-peer online human collaboration */
(function(){
'use strict';
const PEER_SRC='https://unpkg.com/peerjs@1.5.4/dist/peerjs.min.js';
const ROOM_PREFIX='aiteams-room-';
const MAX_CHAT=500;
let peer=null, role='offline', roomCode='', myName='', myPeerId='';
let peers=new Map(), roster=new Map(), humanDirectory=new Map(), pendingQueue=[], processingRemote=false, modal=null, broadcastTimer=null, originalSave=null, saveWrapped=false;

function escOnline(s){return String(s==null?'':s).replace(/[&<>"']/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]})}
function uidOnline(){return (crypto&&crypto.randomUUID)?crypto.randomUUID():String(Date.now()+Math.random())}
function ensurePeerLib(){return new Promise(function(resolve,reject){if(window.Peer)return resolve();const s=document.createElement('script');s.src=PEER_SRC;s.onload=resolve;s.onerror=function(){reject(new Error('کتابخانه اتصال آنلاین بارگذاری نشد.'))};document.head.appendChild(s)})}
function randomCode(){return Math.random().toString(36).slice(2,8).toUpperCase()}
function hostId(code){return ROOM_PREFIX+code}
function inviteUrl(code){const u=new URL(location.href);u.searchParams.set('room',code);return u.toString()}
function setStatus(t,ok){const el=document.getElementById('onlineStatus');if(el)el.innerHTML='<span style="color:'+(ok?'#35d9a8':'#c0cae0')+'">'+escOnline(t)+'</span>'}
function directoryKey(){return 'ai-teams-human-directory-v1-'+roomCode}
function saveHumanDirectory(){if(role!=='host'||!roomCode)return;try{localStorage.setItem(directoryKey(),JSON.stringify(Array.from(humanDirectory.values())))}catch(_){}}
function loadHumanDirectory(){humanDirectory.clear();if(!roomCode)return;try{const a=JSON.parse(localStorage.getItem(directoryKey())||'[]');if(Array.isArray(a))a.forEach(function(p){humanDirectory.set(p.id,p)})}catch(_){}}
function nowIso(){return new Date().toISOString()}
function formatLastSeen(v){if(!v)return 'هنوز ثبت نشده';try{return new Date(v).toLocaleString('fa-IR',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})}catch(_){return v}}
function syncHumanDrawer(){const box=document.getElementById('humanMembersPanel');if(!box)return;const people=Array.from(humanDirectory.values()).sort(function(a,b){return Number(b.online)-Number(a.online)||String(b.lastSeen||'').localeCompare(String(a.lastSeen||''))});if(!people.length){box.innerHTML='<div class="human-empty">هنوز عضو انسانی ثبت نشده است.</div>';return}box.innerHTML=people.map(function(p){const online=!!p.online;return '<div class="human-member"><div class="human-member-head"><span class="human-avatar">👤</span><span class="human-member-name">'+escOnline(p.name)+'</span><span class="human-status '+(online?'online':'offline')+'">'+(online?'● آنلاین':'● آفلاین')+'</span></div><div class="human-last">'+(online?'آنلاین از: '+formatLastSeen(p.onlineSince||p.lastSeen):'آخرین بازدید: '+formatLastSeen(p.lastSeen))+'</div></div>'}).join('')}
function upsertHuman(p){if(!p||!p.id)return;const old=humanDirectory.get(p.id)||{};humanDirectory.set(p.id,Object.assign({},old,p));syncHumanDrawer();if(role==='host')saveHumanDirectory()}
function onlineRosterText(){const people=Array.from(roster.values());if(!people.length)return '';return '\n\nانسان‌های متصل به گفت‌وگوی آنلاین:\n'+people.map(function(p){return '• '+p.name+' | نوع: انسان | وضعیت: آنلاین | شناسه جلسه: '+p.id}).join('\n')+'\nقانون: انسان‌های بالا کاربران واقعی متصل به این اتاق هستند؛ آن‌ها را با اعضای هوش مصنوعی اشتباه نگیر.'}
window.aiTeamsOnlineRosterText=onlineRosterText;

function injectStyles(){if(document.getElementById('onlineTeamStyles'))return;const s=document.createElement('style');s.id='onlineTeamStyles';s.textContent='.online-modal{position:fixed;inset:0;background:rgba(0,0,0,.82);z-index:5000;padding:14px;overflow:auto}.online-box{max-width:760px;margin:25px auto;background:#121a2d;border:1px solid #34425f;border-radius:16px;padding:16px}.online-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.online-code{font-size:22px;letter-spacing:5px;font-weight:900;text-align:center;padding:13px;border:1px dashed #4b96ff;border-radius:12px;background:#0a1121}.online-members{display:grid;gap:7px;max-height:220px;overflow:auto}.online-member{display:flex;align-items:center;gap:8px;border:1px solid #34425f;background:#0d1528;border-radius:10px;padding:9px}.online-dot{width:8px;height:8px;border-radius:50%;background:#35d9a8}.online-actions{display:flex;gap:8px;flex-wrap:wrap}.online-actions .btn{flex:1;min-width:130px}.online-small{font-size:10px;color:#c0cae0;line-height:1.8}@media(max-width:620px){.online-grid{grid-template-columns:1fr}.online-box{margin:8px auto;padding:13px}.online-code{font-size:20px}}';document.head.appendChild(s)}
function openModal(){injectStyles();if(!modal){modal=document.createElement('div');modal.className='online-modal';modal.id='onlineModal';modal.innerHTML='<div class="online-box"><div style="display:flex;justify-content:space-between;align-items:center;gap:8px"><h3 style="margin:0">🌐 همکاری آنلاین</h3><button id="onlineClose" class="icon-btn">✕</button></div><div class="notice" style="margin-top:10px">یک نفر اتاق را می‌سازد و لینک/کد را برای نفرات دیگر می‌فرستد. افراد از گوشی یا کامپیوتر خودشان وارد همان گفت‌وگو می‌شوند.</div><div class="field" style="margin-top:10px"><label>نام شما در گفت‌وگو</label><input id="onlineName" placeholder="مثلاً امیر"></div><div class="online-grid"><div><label class="online-small">کد اتاق</label><input id="onlineCode" placeholder="مثلاً A7K2Q9" maxlength="6" style="text-transform:uppercase;letter-spacing:3px"></div><div><label class="online-small">وضعیت</label><div id="onlineStatus" class="notice" style="margin:0;min-height:42px">متصل نیست</div></div></div><div id="onlineHostArea" style="display:none;margin-top:12px"><div class="online-code" id="onlineCodeView">------</div><div class="online-actions"><button class="btn primary" id="copyInviteBtn">📋 کپی لینک دعوت</button><button class="btn" id="leaveOnlineBtn">خروج از اتاق</button></div><div class="online-small" style="margin-top:7px">کد را برای شخص دیگر بفرست. تا وقتی مرورگر سازنده اتاق باز است، اتاق فعال می‌ماند.</div></div><div id="onlineJoinArea" style="margin-top:12px"><div class="online-actions"><button class="btn primary" id="createRoomBtn">＋ ساخت اتاق جدید</button><button class="btn" id="joinRoomBtn">↗ ورود به اتاق</button></div></div><div id="onlinePeople" style="margin-top:12px;display:none"><div class="section-title">اعضای انسانی آنلاین</div><div id="onlineMembers" class="online-members"></div></div></div>';document.body.appendChild(modal);document.getElementById('onlineClose').onclick=function(){modal.style.display='none'};document.getElementById('createRoomBtn').onclick=createRoom;document.getElementById('joinRoomBtn').onclick=joinRoom;document.getElementById('leaveOnlineBtn').onclick=leaveRoom;document.getElementById('copyInviteBtn').onclick=copyInvite;document.getElementById('onlineCode').oninput=function(){this.value=this.value.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,6)}}modal.style.display='block';const q=new URL(location.href).searchParams.get('room');if(q&&!roomCode)document.getElementById('onlineCode').value=q.toUpperCase().slice(0,6);renderPeople();setOnlineUi()}
function renderPeople(){const box=document.getElementById('onlineMembers'),wrap=document.getElementById('onlinePeople');if(!box||!wrap)return;const people=Array.from(roster.values());wrap.style.display=people.length?'block':'none';box.innerHTML=people.map(function(p){return '<div class="online-member"><span class="online-dot"></span><div style="min-width:0"><b>'+escOnline(p.name)+'</b><div class="online-small">انسان · آنلاین · '+formatLastSeen(p.onlineSince||p.lastSeen)+'</div></div></div>'}).join('');syncHumanDrawer()}
function setOnlineUi(){const hostArea=document.getElementById('onlineHostArea'),joinArea=document.getElementById('onlineJoinArea'),codeView=document.getElementById('onlineCodeView'),codeInput=document.getElementById('onlineCode');if(!hostArea)return;const connected=role!=='offline';hostArea.style.display=connected?'block':'none';joinArea.style.display=connected?'none':'block';if(connected){codeView.textContent=roomCode;codeInput.value=roomCode}renderPeople()}
async function createRoom(){if(role!=='offline')return;myName=(document.getElementById('onlineName').value.trim()||'میزبان').slice(0,40);roomCode=randomCode();myPeerId=hostId(roomCode);loadHumanDirectory();const hostPerson={id:'host-'+roomCode,name:myName,online:true,onlineSince:nowIso(),lastSeen:nowIso(),role:'host'};upsertHuman(hostPerson);await ensurePeerLib();setStatus('در حال ساخت اتاق...',false);peer=new Peer(myPeerId);role='host';peer.on('open',function(){saveHumanDirectory();setStatus('اتاق آماده است؛ منتظر ورود اعضا',true);setOnlineUi();installSaveBridge()});peer.on('connection',function(conn){setupHostConnection(conn)});peer.on('error',function(e){setStatus('خطای اتصال: '+(e.message||e.type||'نامشخص'),false);if(e.type==='unavailable-id'){role='offline';try{peer.destroy()}catch(_){}peer=null;createRoom()}});setOnlineUi()}
function joinRoom(){if(role!=='offline')return;const code=(document.getElementById('onlineCode').value||'').trim().toUpperCase();myName=(document.getElementById('onlineName').value.trim()||'عضو تیم').slice(0,40);if(!/^[A-Z0-9]{6}$/.test(code))return alert('کد اتاق باید ۶ حرف یا عدد باشد.');roomCode=code;ensurePeerLib().then(function(){setStatus('در حال اتصال به اتاق...',false);role='guest';peer=new Peer();peer.on('open',function(){myPeerId=peer.id;const conn=peer.connect(hostId(roomCode),{reliable:true});setupGuestConnection(conn)});peer.on('error',function(e){setStatus('اتصال ناموفق: '+(e.message||e.type||'اتاق پیدا نشد'),false)});setOnlineUi()}).catch(function(e){role='offline';setStatus(e.message,false)})}
function setupHostConnection(conn){let accepted=false;conn.on('open',function(){conn.on('data',function(data){if(data&&data.type==='hello'&&!accepted){const requested=String(data.name||'عضو تیم').slice(0,40);if(!confirm('شخصی با نام «'+requested+'» می‌خواهد وارد اتاق شود. اجازه ورود می‌دهی؟')){conn.send({type:'reject',reason:'ورود توسط میزبان تأیید نشد.'});setTimeout(function(){conn.close()},300);return}accepted=true;const person={id:uidOnline(),name:requested,peerId:conn.peer,online:true,onlineSince:nowIso(),lastSeen:nowIso()};roster.set(conn.peer,person);upsertHuman(person);peers.set(conn.peer,conn);renderPeople();conn.send({type:'welcome',teamName:state.teamName,goal:state.goal,chat:state.chat.slice(-MAX_CHAT),people:Array.from(roster.values()),directory:Array.from(humanDirectory.values())});broadcastRoster();setStatus('اتاق فعال · '+roster.size+' انسان متصل',true);return}if(!accepted)return;if(data&&data.type==='human-message')queueRemoteMessage(conn.peer,String(data.text||'').trim())})});conn.on('close',function(){const person=roster.get(conn.peer);if(person){person.online=false;person.lastSeen=nowIso();upsertHuman(person)}roster.delete(conn.peer);peers.delete(conn.peer);renderPeople();broadcastRoster();if(role==='host')setStatus('اتاق فعال · '+roster.size+' انسان متصل',true)});conn.on('error',function(){})}
function setupGuestConnection(conn){conn.on('open',function(){setStatus('درخواست ورود ارسال شد...',false);conn.send({type:'hello',name:myName})});conn.on('data',function(data){if(!data)return;if(data.type==='reject'){setStatus(data.reason||'ورود رد شد',false);return leaveRoom(false)}if(data.type==='welcome'){roster.clear();humanDirectory.clear();(data.directory||data.people||[]).forEach(function(p){humanDirectory.set(p.id,p)});(data.people||[]).forEach(function(p){roster.set(p.peerId||p.id,p)});state.teamName=data.teamName||state.teamName;state.goal=data.goal||state.goal;state.chat=Array.isArray(data.chat)?data.chat:[];render();setStatus('متصل به اتاق '+roomCode,true);setOnlineUi();return}if(data.type==='chat'){state.chat=Array.isArray(data.chat)?data.chat.slice(-MAX_CHAT):state.chat;renderChat();return}if(data.type==='roster'){roster.clear();(data.people||[]).forEach(function(p){roster.set(p.peerId||p.id,p)});renderPeople();return}if(data.type==='team'){state.teamName=data.teamName||state.teamName;state.goal=data.goal||state.goal;document.getElementById('teamName').value=state.teamName;document.getElementById('goal').value=state.goal}});conn.on('close',function(){const host=Array.from(humanDirectory.values()).find(function(p){return p.role==='host'});if(host){host.online=false;host.lastSeen=nowIso();humanDirectory.set(host.id,host)}setStatus('ارتباط با میزبان قطع شد.',false);role='offline';roster.clear();peers.clear();syncHumanDrawer();setOnlineUi()});conn.on('error',function(e){setStatus('خطای اتصال: '+(e.message||'نامشخص'),false)});peers.set('host',conn)}
function broadcastRoster(){if(role!=='host')return;const m={type:'roster',people:Array.from(roster.values()),directory:Array.from(humanDirectory.values())};peers.forEach(function(c){try{if(c.open)c.send(m)}catch(_){} })}
function broadcastChat(){if(role!=='host')return;clearTimeout(broadcastTimer);broadcastTimer=setTimeout(function(){const m={type:'chat',chat:state.chat.slice(-MAX_CHAT)};peers.forEach(function(c){try{if(c.open)c.send(m)}catch(_){} })},40)}
function broadcastTeam(){if(role!=='host')return;const m={type:'team',teamName:state.teamName,goal:state.goal};peers.forEach(function(c){try{if(c.open)c.send(m)}catch(_){} })}
function installSaveBridge(){if(saveWrapped)return;originalSave=save;save=function(){originalSave();if(role==='host'){broadcastChat();broadcastTeam()}};saveWrapped=true}
function queueRemoteMessage(peerKey,text){if(!text)return;pendingQueue.push({peerKey:peerKey,text:text});processRemoteQueue()}
async function processRemoteQueue(){if(processingRemote||role!=='host')return;processingRemote=true;while(pendingQueue.length){const item=pendingQueue.shift(),person=roster.get(item.peerKey);if(!person)continue;const input=document.getElementById('adminChatInput');if(!input)continue;while(busy)await new Promise(function(r){setTimeout(r,250)});input.value=item.text;try{await runAdminTurn();for(let i=state.chat.length-1;i>=0;i--){if(state.chat[i].type==='user'&&state.chat[i].text===item.text){state.chat[i].name=person.name;state.chat[i].icon='👤';state.chat[i].remoteHumanId=person.id;break}}save()}catch(e){}}processingRemote=false}
function sendGuestMessage(){if(role!=='guest')return;const input=document.getElementById('adminChatInput'),text=(input.value||'').trim(),conn=peers.get('host');if(!text)return;if(!conn||!conn.open)return alert('هنوز به اتاق وصل نیستی.');conn.send({type:'human-message',text:text});input.value=''}
function interceptGuestChat(){const input=document.getElementById('adminChatInput');if(!input)return;document.addEventListener('click',function(e){if(role==='guest'&&e.target.closest&&e.target.closest('#adminChatBtn')){e.preventDefault();e.stopImmediatePropagation();sendGuestMessage()}},true);input.addEventListener('keydown',function(e){if(role==='guest'&&e.key==='Enter'&&!e.shiftKey){e.preventDefault();e.stopImmediatePropagation();sendGuestMessage()}},true)}
async function copyInvite(){try{await navigator.clipboard.writeText(inviteUrl(roomCode));setStatus('لینک دعوت کپی شد.',true)}catch(e){prompt('لینک دعوت را کپی کن:',inviteUrl(roomCode))}}
function leaveRoom(clearUrl){const was=role;if(was==='host'){const me=Array.from(humanDirectory.values()).find(function(p){return p.role==='host'&&p.name===myName});if(me){me.online=false;me.lastSeen=nowIso();upsertHuman(me)}}role='offline';pendingQueue=[];roster.clear();peers.forEach(function(c){try{c.close()}catch(_){}});peers.clear();if(peer){try{peer.destroy()}catch(_){}peer=null}roomCode='';myPeerId='';if(clearUrl!==false){const u=new URL(location.href);u.searchParams.delete('room');history.replaceState({},'',u.toString())}setStatus(was==='host'?'اتاق بسته شد':'از اتاق خارج شدی',false);setOnlineUi();renderPeople();syncHumanDrawer()}
function boot(){syncHumanDrawer();const b=document.getElementById('onlineTeamBtn');if(!b)return;b.onclick=openModal;injectStyles();interceptGuestChat();const q=new URL(location.href).searchParams.get('room');if(q)setTimeout(openModal,500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();